# Generated by Django 5.1 on 2024-09-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
